development:
  adapter: postgresql
  encoding: unicode
  database: moody_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: moody_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: moody_production
  pool: 5
  username: 
  password:
